name: Send Email

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Get Committer Email
        id: commit_email
        run: echo "email=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_OUTPUT
      - name: Display Outputs
        run: |
          echo "Committer Email: ${{ steps.commit_email.outputs.email }}"      
      - name: Call Send Email Action
        uses: ncmuthu/gh-action-send-mail-docker/send-email-action@main
        with:
          to_email: "ncmuthu@gmail.com, ncmuthuaws@gmail.com"
          from_email: ${{ secrets.FROM_EMAIL }}
          smtp_server: ${{ secrets.SMTP_SERVER }}
          smtp_port: ${{ secrets.SMTP_PORT }}
          smtp_username: ${{ secrets.SMTP_USERNAME }}
          smtp_password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Test email using gh action"
          mail_body: | 
            "Hi, 
            Test email from gh01
            Thanks. "
