name: Send Email

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    #container:
      #image: python:3.10.13-slim
    steps:
      - name: Checkout action repository
        uses: actions/checkout@v2      
      - name: Call Send Email Action
        uses: ncmuthu/gh-action-send-mail/send-email-action@dev
        with:
          to_email: ${{ secrets.TO_EMAIL }}
          from_email: ${{ secrets.FROM_EMAIL }}
          smtp_server: ${{ secrets.SMTP_SERVER }}
          smtp_port: ${{ secrets.SMTP_PORT }}
          smtp_username: ${{ secrets.SMTP_USERNAME }}
          smtp_password: ${{ secrets.SMTP_PASSWORD }}        
